# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(max_length=300)),
                ('drop', models.CharField(max_length=300)),
                ('vehicle', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
